# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy only necessary files to build the package
COPY pyproject.toml .
COPY README.md .
COPY src ./src
COPY uv.lock ./uv.lock
COPY LICENSE ./LICENSE

# Install build dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Expose port if using SSE transport (optional)
EXPOSE 9887

# Default command uses stdio transport; configuration can override via Smithery config
CMD ["mcp-jenkins", "--jenkins-url", "http://jenkins", "--jenkins-username", "admin", "--jenkins-password", "admin", "--transport", "stdio"]
